import Head from 'next/head'
import { Inter } from 'next/font/google'
import Layout from '@/components/Layout'
import Image from 'next/image'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'
import TransitionEffect from '@/components/TransitionEffect'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ashrafuj Jaman |Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <TransitionEffect/>
      <main className='flex items-center  text-dark w-full min-h-screen bg-[#EEEEEE]' >
        <Layout className='!pt-0 md:p-16 sm:pt-8'>
          <div className="flex items-center justify-center w-full bg-[#EEEEEE] lg:flex-col">
            <div className='w-1/2 md:w-full' >
              <img
              sizes='(max-width:768px) 100vw, (max-width: 1200px) 50vw' 
              
              src="https://i.ibb.co/9pqMQgw/profile.jpg" alt="" className='w-full h-auto lg:hidden md:inline-block  md:w-full' />

            </div>
            <div className='w-1/2 flex flex-col  items-center self-center lg:w-full lg:text-center' >

              <AnimatedText text="Hi  I'm Ashrfuj Jaman" className='!text-6xl !text-dark  xl:!text-4xl lg:!text-center lg:!text-6xl mg:!text-5xl sm:!text-3xl' />
              <p className='my-4 text-base font-medium md:text-small sm:text-xs'>As a skilled MERN-stack developer, I am dedicated to turning ideas into innovative web applications.
                Explore my latest projects and articles, showcasing my expertise in React.js and web development. </p>
              <div className='flex item-center self-start mt-2 lg:self-center'>
                <Link href='/Ashrafuj jaman tanbin.pdf' target='_blank'
                  download={true}
                  className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold md:p-2 md:text-base hover:bg-light hover:text-dark border-solid border-transparent hover:border-dark border-2 sm:m-5 md:m-5  '
                >Resume <LinkArrow className={"w-6 ml-1"}></LinkArrow>

                </Link>
                <Link href='mailto:ashrafuj.jaman.tanbin1@gmail.com'
                  className='ml-4 text-lg font-medium capitalize text-dark underline md:text-base flex items-center'
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className='absolute right-8 bottom-8 inline-block w-24 md:hidden'>

          <Image src={lightBulb} className='w-full h-auto' alt="" />
        </div>

      </main>
     
    </>
  )
}


// 1.7.36 